---
- name: Debian | Installing mdadm
  ansible.builtin.apt:
    name: "mdadm"
    state: "present"

- name: Debian | Setting distribution-specific facts
  ansible.builtin.set_fact:
    update_initramfs: "update-initramfs -u"
    mdadm_conf: "/etc/mdadm/mdadm.conf"
    mdadm_conf_path: "/etc/mdadm"
